/*
Copyright 2022 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package io.github.cfraser.connekt.knit

import io.github.cfraser.connekt.buildGraph
import io.github.cfraser.connekt.Feature.DIRECTED

fun runExample08() {

val graph = buildGraph(DIRECTED) {
  this += 1 to 2
  this += 2 to 3
  this += 2 to 5
  this += 2 to 6
  this += 3 to 4
  this += 3 to 7
  this += 4 to 3
  this += 4 to 8
  this += 5 to 1
  this += 5 to 6
  this += 6 to 7
  this += 7 to 6
  this += 8 to 4
  this += 8 to 7
}
val components = graph.stronglyConnectedComponents()
println(components)
}
