/*
Copyright 2022 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package io.github.cfraser.connekt.knit.test

import io.kotest.core.spec.style.StringSpec
import kotlinx.knit.test.captureOutput
import kotlinx.knit.test.verifyOutputLines

class Example03Test : StringSpec({
  "verify Example03" {
  captureOutput("Example03") { io.github.cfraser.connekt.knit.runExample03() }.verifyOutputLines(
      "strict graph {",
      "A -- B [weight=3, label=3];",
      "A -- C [weight=1, label=1];",
      "A -- D [weight=5, label=5];",
      "B -- D [weight=6, label=6];",
      "B -- C [weight=2, label=2];",
      "C -- D [weight=4, label=4];",
      "}"
  )
  }
})
